from .types import Claim, DocFile, DocType, LogTrail

def type_claim(file: dict) -> Claim:
    claim = Claim()
    claim.filenumber = file.get("filenumber")
    claim.customername = file.get("customername")
    claim.clientclaimno = file.get("clientclaimno")
    claim.rentername = file.get("rentername")
    claim.ranumber = file.get("ranumber")
    claim.insuredname = file.get("insuredname")
    claim.insurancecompany = file.get("insurancecompany")
    claim.claimnumber = file.get("claimnumber")
    claim.policynumber = file.get("policynumber")
    claim.dateofloss = file.get("dateofloss")
    claim.adjuster = file.get("adjuster")
    claim.adjusterphone = file.get("adjusterphone")
    claim.firstparty = file.get("firstparty")
    claim.thirdparty = file.get("thirdparty")
    claim.cdw = file.get("cdw")
    claim.hc_adj = file.get("hc_adj")
    claim.officephone = file.get("officephone")
    claim.email = file.get("email")
    claim.vin = file.get("vin")
    claim.vehyear = file.get("vehyear")
    claim.vehmake = file.get("vehmake")
    claim.vehmodel = file.get("vehmodel")
    claim.vehedition = file.get("vehedition")
    claim.color = file.get("color")
    claim.platenumber = file.get("platenumber")
    claim.unitnumber = file.get("unitnumber")
    claim.inspectiondate = file.get("inspectiondate")
    claim.estimateamount = file.get("estimateamount")
    claim.totalloss = file.get("totalloss")
    claim.continuedrentalamt = file.get("continuedrentalamt")
    claim.dv_amt = file.get("dv_amt")
    claim.liabilityaccepted = file.get("liabilityaccepted")
    claim.liabilitydenied = file.get("liabilitydenied")
    claim.settlement_pd = file.get("settlement_pd")
    claim.settlement_salvage = file.get("settlement_salvage")
    claim.settlement_cr = file.get("settlement_cr")
    claim.settlement_dv = file.get("settlement_dv")
    claim.settlement_other = file.get("settlement_other")
    claim.settlement_deductable = file.get("settlement_deductable")
    claim.administrativefee = file.get("administrativefee")
    claim.appraisalfee = file.get("appraisalfee")
    claim.datefileclosed = file.get("datefileclosed")
    claim.settlementoffer = file.get("settlementoffer")
    claim.supplement = file.get("supplement")
    claim.settlementtowing = file.get("settlementtowing")
    claim.settlementstorage = file.get("settlementstorage")
    claim.demand_admin_fee = file.get("demand_admin_fee")
    claim.demand_appraisal_fee = file.get("demand_appraisal_fee")
    claim.estimatedate = file.get("estimatedate")
    claim.demanddate = file.get("demanddate")
    claim.policystartdate = file.get("policystartdate")
    claim.policyenddate = file.get("policyenddate")
    claim.vehicleowner = file.get("vehicleowner")
    for doc in file.get("docfiles", []):
        doc_file = DocFile()
        doc_file.doctype = DocType(doc.get("doctype"))
        doc_file.dateadded = doc.get("dateadded")
        doc_file.user = doc.get("user")
        doc_file.notes = doc.get("notes")
        doc_file.filename = doc.get("filename")
        claim.docfiles.append(doc_file)
    for logtrail in file.get("logtrail", []):
        log_entry = LogTrail()
        log_entry.date = logtrail.get("date")
        log_entry.activity = logtrail.get("activity")
        log_entry.user = logtrail.get("user")
        claim.logtrail.append(log_entry)
    return claim